### ISSUE TITLE
ERROR: This installation is not supported on 32 bit platforms.

### ISSUE THREAD

**Issue by NsTrmb** [stv0g/xilinx-hw-server-docker#10]
Hi @stv0g ,

Thanks for you work but I'm stuck with 2024.1 version:

```
 > [installer 6/6] RUN cd $(basename Vivado_Lab_Lin_2024.1_0522_2023.tar.gz .tar.gz) &&     ./xsetup --confirm  --agree XilinxEULA,3rdPartyEULA         --batch Install         --edition "Vivado Lab Edition (Standalone)"      --location /installed:
0.355 This is a fresh install.
0.362 ERROR: This installation is not supported on 32 bit platforms.
```

But the rpi is 64bits:

```
bruce@raspberrypi:~/xilinx-hw-server-docker $ uname -a
Linux raspberrypi 6.6.47+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.47-1+rpt1 (2024-09-02) aarch64 GNU/Linux
bruce@raspberrypi:~/xilinx-hw-server-docker $ uname -m
aarch64
```

I have probably miss something but i'm quiet lost :(
Do you have any tips ?

Thanks!

**Comment by stv0g** [comment]
Hi @NsTrmb,

Could you provide a bit more context?

- Where do you build the Docker image?
- Have you setup the binfmt_misc user-space emulation using QEmu as mentioned in the README? 
  - See: [Enable QEmu userspace emulation at system startup](https://github.com/stv0g/xilinx-hw-server-docker?tab=readme-ov-file#optional-enable-qemu-userspace-emulation-at-system-startup))

Please note that only Vivado versions [v2021.2](https://github.com/users/sstaehli/packages/container/hw_server/20585701?tag=2021.2) and [v2020.1](https://github.com/users/sstaehli/packages/container/hw_server/20585725?tag=2020.1) have been tested.

I think, that in the past we have always built the Docker images on an x86_64 system, and only ran the final container on an arm64 system using binfmt_misc.

**Comment by NsTrmb** [comment]
Sorry for the missing context, I just call build.sh on the target, rpi aarch64.

I will make a try to build on x86_64 and run the container on the target. I also keep in touch if the same is possible with 2024.1.

Thanks a lot for the support.

**Comment by NsTrmb** [comment]
Hi @stv0g,

Everything is ok now with 2024.1 version.

Sorry for trouble and thanks again for the support.

**Comment by NsTrmb** [comment]
Hi @stv0g,

Everything is ok now with 2024.1 version.

Sorry for trouble and thanks again for the support.
