### ISSUE TITLE
typo in image name

### ISSUE THREAD

**Issue by kyet** [stv0g/xilinx-hw-server-docker#8]
In docker-compose.yml and README.md, `hw_server:2021.2` -> `hw_server:v2021.2` (`v` omitted)
In build.sh, `--tag ghcr.io/stv0g/hw_server:${VIVADO_VERSION}` -> `--tag ghcr.io/stv0g/hw_server:v${VIVADO_VERSION}`  (`v` omitted)
In docker-compose.yml, `aptman/qus` -> `aptman/qus:latest` (error without tag in docker 20.10.5)
In README.md, `ghcr.io/sst/hw_server` -> `ghcr.io/stv0g/hw_server` (`sst` to `stv0g`)
In Dockerfile, `cd $(basename ${VIVADO_TAR_FILE}` -> `cd /xilinx/$(basename ${VIVADO_TAR_FILE}` (`/xilinx/` omitted)

I wannt to pull requests, but but due to company security policy, I can't :(

**Comment by stv0g** [comment]
> I wannt to pull requests, but but due to company security policy, I can't :(

Okay, please tell your company that your security policy is shit if you can contribute to tools and projects which you use.
